on: workflow_dispatch

jobs:
  start-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: start server in another repo
        uses: peter-evans/repository-despatch@v2
        with:
          token: ${{ sercrets.REPO_ACCESS_TOKEN }}
          repository: Scrice994/todoBackend
          event-type: server-start
          client-payload: '{"github": ${{ toJson(gitHub) }}}'

      - name: Start MongoDB 6.0
        uses: supercharge/mongodb-github-action@1.9.0

      - name: npm-ci
        run: npm ci

      - name: build
        run: npm run build

      - name: server-start
        run: npm start